// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations need a DIRECT connection (advisory locks, DDL). On Supabase the
    // runtime DATABASE_URL points at the transaction pooler (6543), which can't
    // run `prisma migrate` — so prefer DIRECT_URL here when set. Locally there is
    // no DIRECT_URL and this falls back to DATABASE_URL unchanged.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
